<!DOCTYPE html>
<html lang="en">
<head>
    <title>Book page</title>

    <link rel="stylesheet" href="../css/tables.css"/>
    <link rel="stylesheet" href="../css/book_form.css"/>
    <link rel="stylesheet" href="../css/delete_book.css"/>

    <script type="module" src="../scripts/ajax.js"></script>
    <script type="module" src="../scripts/books.js"></script>

</head>

<body>
<div id="app-container"></div>
</body>
</html>